spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: "{ciper}64a940bdf571a4fccde25917423aa9eca22f85b3c4b50098b687d6887399bf9b"

token:
  expiration_time: 864000000
  secret: this_is_my_prod_token_secret

gateway:
  ip: 192.168.0.8
