spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: test1234

token:
  expiration_time: 864000000
  secret: this_is_my_prod_token_secret

gateway:
  ip: 192.168.0.8
